# Generated by Django 3.0.5 on 2020-04-26 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Station', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stationdrone',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stationrobot',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
