# Generated by Django 3.0.5 on 2020-04-29 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('capacity', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Robot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('capacity', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
            ],
        ),
    ]
